services:
  - type: web
    name: jemidapa-master-challenge
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20.10.0"
      # - key: VITE_GEMINI_API_KEY
      #   value: "ENTER_YOUR_GEMINI_API_KEY_HERE"
